main: rush.Main
version: 1.0
name: System

commands:
  alerta:
    description: Limpa o chat do servidor.
    aliases: []
    permission: system.alerta
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  clearchat:
    description: Limpa o chat do servidor.
    aliases: [cc]
    permission: system.clearchat
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  cores:
    description: Mostra a lista de cores do minecraft.
    aliases: [colors]
    permission: system.cores
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  delwarp:
    description: Deleta uma warp.
    aliases: []
    permission: system.delwarp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  divulgar:
    description: Divulga um link no chat.
    aliases: []
    permission: system.divulgar
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  executarsom:
    description: Executa um som para um player ou para todo server.
    aliases: [playsound, som]
    permission: system.executarsom
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  lixo:
    description: Abre a lixeira virtual.
    aliases: [lixeira]
    permission: system.lixo
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  luz:
    description: Liga e desliga a lanterna.
    aliases: [lanterna]
    permission: system.luz
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  mundovip:
    description: Teleporta até o mundo vip.
    aliases: [vip]
    permission: system.mundovip
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  online:
    description: Mostra a quantidade de players online no servidor.
    aliases: []
    permission: system.online
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  ping:
    description: Mostra o seu ping atual.
    aliases: []
    permission: system.ping
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setmundovip:
    description: Define a mundo vip e não vip do servidor.
    aliases: []
    permission: system.setmundovip
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setspawn:
    description: Define o spawn do servidor.
    aliases: []
    permission: system.setspawn
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setwarp:
    description: Define uma warp.
    aliases: []
    permission: system.setwarp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  sgive:
    description: Envia geradores para um player.
    aliases: []
    permission: system.sgive
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  slime:
    description: Verifica se você esta em uma slimechunk.
    aliases: [slimechunk]
    permission: system.slime
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  spawn:
    description: Teleporta até o spawn.
    aliases: []
    permission: system.spawn
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  title:
    description: Envia um title para um player ou para todo servidor.
    aliases: [tm]
    permission: system.title
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  warp:
    description: Teleporta até uma warp.
    aliases: []
    permission: system.warp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  warps:
    description: Mostra a lista de todas as warps do servidor.
    aliases: []
    permission: system.warps
    permission-message: "§cVocê não tem permissão para utilizar este comando."

permissions:
  system.alerta:
    description: Permissão para enviar um alerta no servidor.
    default: op
  system.clearchat:
    description: Permissão para limpar o chat do servidor.
    default: op
  system.cores:
    description: Permissão para ver a lista de cores do minecraft.
    default: true
  system.cornabigorna:
    description: Permissão para renomear itens com cores.
    default: false
  system.cornaplaca:
    description: Permissão para renomear itens com cores.
    default: false
  system.delwarp:
    description: Permissão para deletar uma warp.
    default: op
  system.divulgar:
    description: Permissão para divulgar um link no chat.
    default: op
  system.executarsom:
    description: Permissão para enviar um som para um player ou para todo servidor.
    default: op
  system.lixo:
    description: Permissão para abrir a lixeira virtual.
    default: true
  system.luz:
    description: Permissão para ligar e desligar a lanterna.
    default: true
  system.mundovip:
    description: Permissão para usar o comando /mundovip.
    default: true
  system.online:
    description: Permissão para ver o número de players online no servidor.
    default: true
  system.ping:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: true
  system.semdelay:
    description: Permissão para se teleportar sem ter que esperar o delay.
    default: op
  system.setmundovip:
    description: Permissão para definir a area vip e não vip do servidor.
    default: op
  system.setspawn: 
    description: Permissão para definir o spawn do servidor
    default: op
  system.setwarp:
    description: Permissão para definir uma warp.
    default: op
  system.sgive:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: op
  system.slime:
    description: Permissão para verificar se você esta em uma slimechunk.
    default: true
  system.spawn:
    description: Permissão para se teleportar até o spawn.
    default: true
  system.title:
    description: Permissão para enviar um title para todo servidor.
    default: op
  system.vip:
    description: Permissão para se teleportar até a area vip.
    default: op
  system.warp:
    description: Permissão para se teleportar até a area vip.
    default: true
  system.warps:
    description: Permissão para se teleportar até a area vip.
    default: true
  system.chat.cor1:
    default: false
  system.chat.cor2:
    default: false
  system.chat.cor3:
    default: false
  system.chat.cor4:
    default: false
  system.chat.cor5:
    default: false
  system.chat.cor6:
    default: false
  system.chat.cor7:
    default: false
  system.chat.cor8:
    default: false
  system.chat.cor9:
    default: false
  system.chat.cor10:
    default: false
  system.chat.destaque:
    default: false
  system.bypass.comandobloqueado:
    description: Permissão para usar comandos que foram bloqueados.
    default: false
  system.bypass.containerbloqueado:
    description: Permissão para abrir um inventario que foi bloqueado.
    default: false
  system.bypass.craftbloqueado:
    description: Permissão para craftar itens que foram bloqueados.
    default: false
  system.bypass.entraremveiculos:
    description: Permissão para entrar em veiculos mesmo se estiver bloqueado.
    default: false
  system.bypass.entrarnacama:
    description: Permissão para entrar na cama mesmo se ela estiver bloqueada.
    default: false
  system.bypass.placabloqueada:
    description: Permissão para escrever nas placas mesmo se elas estiverem bloqueadas.
    default: false
  system.bypass.shiftemcontainer:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.teleportarporportal:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.usarnametag:
    description: Permissão para usar a NameTag mesmo se ela estiver bloqueada.
    default: false

  system.bypass.all:
    description: Permissão para burlar todos os recursos do plugin.
    default: false
    children:
      system.bypass.comandobloqueado: true
      system.bypass.containerbloqueado: true
      system.bypass.craftbloqueado: true
      system.bypass.entraremveiculos: true
      system.bypass.entrarnacama: true
      system.bypass.placabloqueada: true
      system.bypass.shiftemcontainer: true
      system.bypass.teleportarporportal: true
      system.bypass.usarnametag: true

  system.admin:
    description: Acesso a todos os comandos do plugin.
    default: op
    children:
      system.alerta: true
      system.clearchat: true
      system.cores: true
      system.cornaplaca: true
      system.delwarp: true
      system.divulgar: true
      system.executarsom: true
      system.lixo: true
      system.luz: true
      system.mundovip: true
      system.online: true
      system.ping: true
      system.semdelay: true
      system.setmundovip: true
      system.setspawn: true
      system.setwarp: true
      system.sgive: true
      system.slime: true
      system.spawn: true
      system.title: true
      system.vip: true
      system.warp: true
      system.warps: true