############################################################
# +------------------------------------------------------+ #
# |              Recuros Adicionais (Addons)             | #
# +------------------------------------------------------+ #
############################################################
AtivarAddons:
  Legendchat: true
  mcMMO: true

############################################################
# +------------------------------------------------------+ #
# |                  Recursos Anti-BUG                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Abrir-Bigorna: true
Bloquear-Abrir-Funil: true
Bloquear-Cama: true
Bloquear-Subir-Em-Veiculos: true
Bloquear-NameTag: true
Bloquear-Passar-Da-Borda: true
Bloquear-Xp-Ao-Quebrar-Mob-Spawners: true
Bloquear-Subir-No-Teto-Nether: true
EnderPearl-Cooldown: 
  Ativar: true
  Cooldown: 5

Bloquear-Abrir-Containers:
  Ativar: true
  Containers:
  - 'ANVIL'
  - 'ENCHANTING'
  - 'HOPPER'
  # Lista de containers: https://ghostbin.com/paste/mxjom

Bloquear-Shift-Em-Containers:
  Ativar: True
  Containers:
  - 'ENDER_CHEST'
  - 'BEACON'
  - 'BREWING'
  # Lista de containers: https://ghostbin.com/paste/mxjom

############################################################
# +------------------------------------------------------+ #
# |                  Recursos Anti-LAG                   | #
# +------------------------------------------------------+ #
############################################################
Desativar-Mobs-Naturais: true
Desativar-Propagacao-Do-Fogo: true
Desativar-Queda-Das-Folhas: true
Desativar-Queda-Da-Areia: true
Desativar-Flow-Da-Agua-E-Lava: true
Desativar-Chuva: true

############################################################
# +------------------------------------------------------+ #
# |                   Recursos Gerais                    | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Cair-No-Void: true
Desativar-Ciclo-Do-Dia: true
Desativar-Dano-Do-EnderDragon: true
Desativar-Dano-Do-Whither: true
Desativar-Fome-Nos-Mundos: true
Desativar-Mensagem-De-Entrada: true
Desativar-Mensagem-De-Morte: true
Desativar-Mensagem-De-Saida: true
Entrar-No-Spawn-Ao-Logar: true
Bloquear-Criar-Portal: true
Bloquear-Teleport-Por-Portal:
  Ativar: true
  NetherPortal: true
  EndPortal: false

############################################################
# +------------------------------------------------------+ #
# |                  Recursos Adicionais                 | #
# +------------------------------------------------------+ #
############################################################
Cores-Na-Bigorna: true
Cores-Na-Placa: true

############################################################
# +------------------------------------------------------+ #
# |                 Sistemas de Spawners                 | #
# +------------------------------------------------------+ #
############################################################
Sistema-De-Spawners: true
Bloquear-Trocar-Tipo-Do-Spawner-Com-Ovo: true
Dropar-Spawner-Ao-Explodir: true
Chance-De-Dropar-Ao-Explodir: 60

############################################################
# +------------------------------------------------------+ #
# |                   Spawn do Servidor                  | #
# +------------------------------------------------------+ #
############################################################
Spawn:
  world: world
  x: 6.890845736296801
  y: 4.0
  z: 4.289127650244211
  yaw: 112.50008
  pitch: 2.1000016

############################################################
# +------------------------------------------------------+ #
# |                   Motd do Servidor                   | #
# +------------------------------------------------------+ #
############################################################
Motd:
  Ativar: true
  Linha1: "§f§lGamer's§9§lBoard §7www.gamersboard.com.br"
  Linha2: "§fA sua comunidade gamer!"
  Maximo-De-Players: 340

############################################################
# +------------------------------------------------------+ #
# |                   Bloquear Comandos                  | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Comandos: true
Lista-Dos-Comandos-Bloqueados:
  - '/pl'
  - '/plugins'
 
############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Crafts                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Crafts: true
Lista-Dos-Crafts-Bloqueados: 
  - '333'
  - '145'
  - '52'
  # Lista de IDs: https://www.minecraftinfo.com/idlist.htm

############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Placas                   | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Placas: true
Bloquear-Todas-As-Palavras: false
Bloquear-Apenas-Algumas-Palavras: true
Lista-Das-Palavras-Bloqueadas:
  - 'AdminShop'
  - '&0AdminShop'
  - 'puta'

############################################################
# +------------------------------------------------------+ #
# |                         mcMMO                        | #
# +------------------------------------------------------+ #
############################################################
mcTopTag:
  Tempo-De-Checagem: 300
  Tag: '&9[⚒] '

############################################################
# +------------------------------------------------------+ #
# |                      LegendChat                      | #
# +------------------------------------------------------+ #
############################################################
CorAutomatica:
  Cor1: "§6"
  Cor2: "§4"
  Cor3: "§c"
  Cor4: "§2"
  Cor5: "§e"
  Cor6: "§a"
  Cor7: "§b"
  Cor8: "§3"
  Cor9: "§d"
  Cor10: "§f"
  #Permissão para usar a cor automatica nas frases: system.cor1 // system.cor2 // etc...
  #Permissão para escrever em destaque no /g: system.destaquechat

############################################################
# +------------------------------------------------------+ #
# |                     Auto-Anunciar                    | #
# +------------------------------------------------------+ #
############################################################
Auto-Anuncio: true
Destacar-Anuncio: true
Delay-Entre-Anuncios: 5
Reproduzir-Som-No-Anuncio: true
Lista-De-Anuncios:
  - '&e&l[Anuncio] &eInscreva-se em nosso canal e fique por dentro de tudo &b&nhttp://bit.ly/hypixel&e!'
  - '&e&l[Anuncio] &eAdquira já seu vip através do nosso site &b&nhttps://hypixel.net/&e!'
  - '&e&l[Anuncio] &eAcesse já nosso fórum e fique por dentro de tudo &b&nhttps://hypixel.net/forums/&e!'
  - '&e&l[Anuncio] &eO evento base perdida ira ocorrer nesta semana! Saiba mais &b&nhttp://bit.ly/karaoke&e!'

############################################################
# +------------------------------------------------------+ #
# |                      ScoreBoard                      | #
# +------------------------------------------------------+ #
############################################################
ScoreBoard:
  Ativar: true
  Titulo: "  §f§lGamer's§9§lBoard  "
  Linhas:
  - '§bOlá %player%!'
  - '§bSejá bem vindo ao'
  - '§d§l> master-mc.net <'
  - '§r'
  - '§aACESSE NOSSO SITE:'
  - '§7gamersboard.com.br'