main: rush.Main
version: 1.0
name: System
softdepend: [Legendchat, mcMMO]

commands:
  alerta:
    description: Limpa o chat do servidor.
    aliases: []
    permission: system.alerta
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  back:
    description: Volta ao local anterior do seu teleporte.
    aliases: []
    permission: system.back
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  chapeu:
    description: Veste um chapeu.
    aliases: [hat]
    permission: system.chapeu
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  clear:
    description: Limpa o seu inventario.
    aliases: [cc]
    permission: system.clear
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  clearchat:
    description: Limpa o chat do servidor.
    aliases: [cc]
    permission: system.clearchat
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  compactar:
    description: Compactar todos os itens do inventario.
    aliases: [block, condense]
    permission: system.compactar
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  cores:
    description: Mostra a lista de cores do minecraft.
    aliases: []
    permission: system.cores
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  craft:
    description: Abre uma bancada de trabalho virtual.
    aliases: [workbench]
    permission: system.craft
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  criarkit:
    description: Cria um kit.
    aliases: [createkit]
    permission: system.criarkit
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  delhome:
    description: Deleta uma home.
    aliases: []
    permission: system.delhome
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  delkit:
    description: Deleta um kit.
    aliases: [apagarkit]
    permission: system.delkit
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  delwarp:
    description: Deleta uma warp.
    aliases: []
    permission: system.delwarp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  derreter:
    description: Derrete todos os minérios do inventario.
    aliases: []
    permission: system.derreter
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  divulgar:
    description: Divulga um link no chat.
    aliases: []
    permission: system.divulgar
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  echest:
    description: Abre o enderchest virtual.
    aliases: [ec]
    permission: system.echest
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  editaritem:
    description: Edita o item que esta na mão.
    aliases: [renomear, lore]
    permission: system.editaritem
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  editarkit:
    description: Edita um kit criado.
    aliases: [editkit]
    permission: system.editarkit
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  executarsom:
    description: Executa um som para um player ou para todo server.
    aliases: [playsound, som]
    permission: system.executarsom
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  fly:
    description: Ativa ou desativa o modo fly.
    aliases: [voar]
    permission: system.fly
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  gamemode:
    description: Altera o seu modo de jogo.
    aliases: [gm]
    permission: system.gamemode
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  home:
    description: Teleporta até uma home.
    aliases: []
    permission: system.home
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  homes:
    description: Mostra a lista de homes salvas.
    aliases: []
    permission: system.homes
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  invsee:
    description: Abre o inventario de um player.
    aliases: [inv]
    permission: system.invsee.mod
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  kit:
    description: Pega um kit.
    aliases: []
    permission: system.kit
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  kits:
    description: Lista todos os kits disponiveis.
    aliases: []
    permission: system.kits
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  lixo:
    description: Abre a lixeira virtual.
    aliases: [lixeira]
    permission: system.lixo
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  luz:
    description: Liga e desliga a lanterna.
    aliases: [lanterna]
    permission: system.luz
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  mundovip:
    description: Teleporta até o mundo vip.
    aliases: [vip]
    permission: system.mundovip
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  online:
    description: Mostra a quantidade de players online no servidor.
    aliases: []
    permission: system.online
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  particular:
    description: Define uma home como particular.
    aliases: []
    permission: system.particular
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  ping:
    description: Mostra o seu ping atual.
    aliases: []
    permission: system.ping
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  publica:
    description: Define uma home como publica.
    aliases: []
    permission: system.publica
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  sethome:
    description: Define uma home.
    aliases: []
    permission: system.sethome
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setmundovip:
    description: Define a mundo vip e não vip do servidor.
    aliases: []
    permission: system.setmundovip
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setspawn:
    description: Define o spawn do servidor.
    aliases: []
    permission: system.setspawn
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  setwarp:
    description: Define uma warp.
    aliases: []
    permission: system.setwarp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  sgive:
    description: Envia geradores para um player.
    aliases: []
    permission: system.sgive
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  skull:
    description: Pega a cabeça de um player.
    aliases: [head, cabeca]
    permission: system.skull
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  slime:
    description: Verifica se você esta em uma slimechunk.
    aliases: [slimechunk]
    permission: system.slime
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  spawn:
    description: Teleporta até o spawn.
    aliases: []
    permission: system.spawn
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  title:
    description: Envia um title para um player ou para todo servidor.
    aliases: [tm]
    permission: system.title
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  warp:
    description: Teleporta até uma warp.
    aliases: []
    permission: system.warp
    permission-message: "§cVocê não tem permissão para utilizar este comando."
  warps:
    description: Lista todas as warps disponiveis.
    aliases: []
    permission: system.warps
    permission-message: "§cVocê não tem permissão para utilizar este comando."

permissions:
  system.alerta:
    description: Permissão para enviar um alerta no servidor.
    default: op
  system.chapeu:
    description: Permissão para vestir um chapeu.
    default: op
  system.back:
    description: Permissão para voltar ao local alterior do seu teleporte.
    default: op
  system.clear: 
    description: Permissão para limpar o seu inventario.
    default: op
  system.clear.outros: 
    description: Permissão para limpar o inventario de outras pessoas.
    default: op
  system.clearchat:
    description: Permissão para limpar o chat do servidor.
    default: op
  system.compactar:
    description: Permissão para compactar todos os itens do inventario.
    default: op
  system.cores:
    description: Permissão para ver a lista de cores do minecraft.
    default: true
  system.cornabigorna:
    description: Permissão para renomear itens com cores.
    default: op
  system.cornaplaca:
    description: Permissão para renomear itens com cores.
    default: op
  system.craft:
    description: Permissão para abrir uma bancada de trabalho virtual.
    default: op
  system.criarkit:
    description: Permissão para criar um kit.
    default: op
  system.delhome:
    description: Permissão para definir uma home.
    default: true
  system.delkit:
    description: Permissão para deletar um kit.
    default: op
  system.delwarp:
    description: Permissão para deletar uma warp.
    default: op
  system.derreter: 
    description: Permissão para derreter todos os minérios do inventario.
    default: op
  system.divulgar:
    description: Permissão para divulgar um link no chat.
    default: op
  system.echest:
    description: Permissão para abrir o enderchest virtual.
    default: op
  system.echest.mod:
    description: Permissão para ver o enderchest virtual de outras pessoas.
    default: op
  system.echest.admin:
    description: Permissão para editar o enderchest virtual de outras pessoas.
    default: op
  system.editaritem:
    description: Permissão para editar o item que esta segurando na mão.
    default: op
  system.editarkit: 
    description: Permissão para editar um kit criado.
    default: op
  system.executarsom:
    description: Permissão para enviar um som para um player ou para todo servidor.
    default: op
  system.fly:
    description: Permissão para ativar ou desativar o seu modo fly.
    default: op
  system.fly.outros:
    description: Permissão para ativar ou desativar o fly de outras pessoas.
    default: op
  system.gamemode:
    description: Permissão para poder alterar o seu modo de jogo.
    default: op
  system.gamemode.outros:
    description: Permissão para poder alterar o modo de jogo de outras pessoas.
    default: op
  system.gamemode.survival: 
    description: Permissão para alterar o seu modo de jogo para survival.
    default: op
  system.gamemode.creative: 
    description: Permissão para alterar o seu modo de jogo para criativo.
    default: op
  system.gamemode.adventure: 
    description: Permissão para alterar o seu modo de jogo para aventura.
    default: op
  system.gamemode.spectator: 
    description: Permissão para alterar o seu modo de jogo para espectador.
    default: op
  system.home:
    description: Permissão para se teleportar até uma home.
    default: true
  system.home.admin:
    description: Permissão para ver e para se teleportar para as homes privadas de alguem.
    default: op
  system.invsee.mod: 
    description: Permissão para abrir o inventario de um player.
    default: op
  system.invsee.admin: 
    description: Permissão para editar o inventario de um player.
    default: op
  system.kit:
    description: Permissão para utilizar o comando /kit.
    default: true
  system.kit.all: 
    description: Permissão para poder pegar qualquer kit.
    default: op
  system.kits:
    description: Permissão para ver a lista de kits disponiveis.
    default: true
  system.homes:
    description: Permissão para ver a lista de homes.
    default: true
  system.lixo:
    description: Permissão para abrir a lixeira virtual.
    default: true
  system.luz:
    description: Permissão para ligar e desligar a lanterna.
    default: true
  system.manterxp:
    description: Permissão para não perder xp ao morrer.
    default: op
  system.mundovip:
    description: Permissão para usar o comando /mundovip.
    default: true
  system.online:
    description: Permissão para ver o número de players online no servidor.
    default: true
  system.particular:
    description: Permissão para definir uma home como particular.
    default: true
  system.ping:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: true
  system.publica:
    description: Permissão para definir uma home como publica.
    default: true
  system.semdelay:
    description: Permissão para se teleportar sem ter que esperar o delay.
    default: op
  system.sethome:
    description: Permissão para definir uma home.
    default: true
  system.setmundovip:
    description: Permissão para definir a area vip e não vip do servidor.
    default: op
  system.setspawn: 
    description: Permissão para definir o spawn do servidor.
    default: op
  system.setwarp:
    description: Permissão para definir uma warp.
    default: op
  system.sgive:
    description: Permissão para ver o seu ping ou o ping de outro player.
    default: op
  system.slime:
    description: Permissão para verificar se você esta em uma slimechunk.
    default: true
  system.spawn:
    description: Permissão para se teleportar até o spawn.
    default: true
  system.title:
    description: Permissão para enviar um title para todo servidor.
    default: op
  system.vip:
    description: Permissão para se teleportar até a area vip.
    default: op
  system.warp:
    description: Permissão para se teleportar para uma warp.
    default: true
  system.warps:
    description: Permissão para ver a lista de warps disponiveis.
    default: true
  system.chat.cor1:
    default: false
  system.chat.cor2:
    default: false
  system.chat.cor3:
    default: false
  system.chat.cor4:
    default: false
  system.chat.cor5:
    default: false
  system.chat.cor6:
    default: false
  system.chat.cor7:
    default: false
  system.chat.cor8:
    default: false
  system.chat.cor9:
    default: false
  system.chat.cor10:
    default: false
  system.chat.destaque:
    default: false
  system.bypass.comandobloqueado:
    description: Permissão para usar comandos que foram bloqueados.
    default: false
  system.bypass.containerbloqueado:
    description: Permissão para abrir um inventario que foi bloqueado.
    default: false
  system.bypass.craftbloqueado:
    description: Permissão para craftar itens que foram bloqueados.
    default: false
  system.bypass.delaykit:
    description: Permissão para pegar um kit sem precisar esperar o delay.
    default: op
  system.bypass.entraremveiculos:
    description: Permissão para entrar em veiculos mesmo se estiver bloqueado.
    default: false
  system.bypass.entrarnacama:
    description: Permissão para entrar na cama mesmo se ela estiver bloqueada.
    default: false
  system.bypass.placabloqueada:
    description: Permissão para escrever nas placas mesmo se elas estiverem bloqueadas.
    default: false
  system.bypass.shiftemcontainer:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.teleportarporportal:
    description: Permissão para usar o shift em containers mesmo se estiver bloqueado.
    default: false
  system.bypass.usarnametag:
    description: Permissão para usar a NameTag mesmo se ela estiver bloqueada.
    default: false

  system.gamemode.all:
    description: Permissão para poder entrar em todos os modos de jogo.
    default: false
    children:
      system.gamemode.survival: true
      system.gamemode.creative: true
      system.gamemode.adventure: true
      system.gamemode.spectator: true

  system.bypass.all:
    description: Permissão para burlar todos os recursos do plugin.
    default: false
    children:
      system.bypass.comandobloqueado: true
      system.bypass.containerbloqueado: true
      system.bypass.craftbloqueado: true
      system.bypass.delaykit: true
      system.bypass.entraremveiculos: true
      system.bypass.entrarnacama: true
      system.bypass.placabloqueada: true
      system.bypass.shiftemcontainer: true
      system.bypass.teleportarporportal: true
      system.bypass.usarnametag: true

  system.admin:
    description: Acesso a todos os recursos do plugin.
    default: op
    children:
      system.alerta: true
      system.back: true
      system.chapeu: true
      system.clear: true
      system.clear.outros: true
      system.clearchat: true
      system.compactar: true
      system.cores: true
      system.cornabigorna: true
      system.cornaplaca: true
      system.criarkit: true
      system.craft: true
      system.delhome: true
      system.delkit: true
      system.delwarp: true
      system.derreter: true
      system.divulgar: true
      system.echest: true
      system.echest.mod: true
      system.echest.admin: true
      system.editaritem: true
      system.editarkit: true
      system.executarsom: true
      system.fly: true
      system.fly.outros: true
      system.gamemode: true
      system.gamemode.outros: true
      system.gamemode.all: true
      system.home: true
      system.home.admin: true
      system.homes: true
      system.invsee.mod: true
      system.invsee.admin: true
      system.kit: true
      system.kit.all: true
      system.kits: true
      system.lixo: true
      system.luz: true
      system.mundovip: true
      system.online: true
      system.particular: true
      system.ping: true
      system.publica: true
      system.semdelay: true
      system.sethome: true
      system.setmundovip: true
      system.setspawn: true
      system.setwarp: true
      system.sgive: true
      system.skull: true
      system.slime: true
      system.spawn: true
      system.title: true
      system.vip: true
      system.warp: true
      system.warps: true