file-version: 3
############################################################
# +------------------------------------------------------+ #
# |              Recuros Adicionais (Addons)             | #
# +------------------------------------------------------+ #
############################################################
AtivarAddons:
  MassiveFactions: true 
  #-> O Addon do Massive serve para não setar home nas terras dos inimigos
  
  LegendChat: true
  #-> O Addon do LegendChat serve para as Tags(McTop e Magnata), para o sistema de destacar 
  #   a mensagem dos master e colocar cor automatica na mensagem.
  
  McMMO: true
  #-> O Addon do McMMO serve para mostra o XP na ActionBar e para anunicar quando upa 100 niveis
  #   e criar a Tag McTop no LegendChat
  
  Vault: true
  #-> O Addon do Vault serve para a tag criar a Tag Magnata no LegendChat

############################################################
# +------------------------------------------------------+ #
# |                  Recursos Anti-BUG                   | #
# +------------------------------------------------------+ #
############################################################
# Este recurso bloqueia o player de deitar em camas
# OBS: Para burlar use a permissão: system.bypass.entrarnacama 
Bloquear-Cama: true

# Este recurso bloqueia o player de subir em veiculos
# OBS: Para burlar use a permissão: system.bypass.entraremveiculos
Bloquear-Subir-Em-Veiculos: true

# Este recurso bloqueia o player de renomear mobs com NameTags
# OBS: Para burlar use a permissão: system.bypass.usarnametag
Bloquear-NameTag: false

# Este recurso bloqueia o player passadr da borda com EnderPearls
Bloquear-Passar-Da-Borda: true

# Este recurso bloquia o player de subir a cima 
Bloquear-Subir-No-Teto-Nether: true

# Este recurso adiciona um delay na EnderPearl
EnderPearl-Cooldown: 
  Ativar: true
  Cooldown: 5 #segundos

# Este recurso impede o player de abrir containers como baús, bigornas etc.
# OBS: Para burlar use a permissão: system.bypass.containerbloqueado
Bloquear-Abrir-Containers: 
  Ativar: false
  Containers:
  - 'ANVIL'
  - 'ENCHANTING'
  - 'HOPPER'
  # Lista de containers da 1.8: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/event/inventory/InventoryType.html

# Este recurso impede o player de usar o SHIFT_CLICK em containers.
# OBS: Para burlar use a permissão: system.bypass.shiftemcontainer
Bloquear-Shift-Em-Containers:
  Ativar: false
  Containers:
  - 'ENDER_CHEST'
  - 'BEACON'
  - 'BREWING'
  # Lista de containers da 1.8: http://docs.codelanx.com/Bukkit/1.8/org/bukkit/event/inventory/InventoryType.html

# É recomedando ativar isto para quem usa o BlackMarket ou BlackEconomy... 
# Isto previne o bug do valor NaN ou null
Bloquear-Money-Invalido: false
Comandos-Que-Envolvem-Money:
  - 'coins'
  - 'money'
  - 'mercado'
  - 'eco'
  - 'pay'

############################################################
# +------------------------------------------------------+ #
# |             Desativar Recursos do Mapa               | #
# +------------------------------------------------------+ #
############################################################
# Este recurso bloqueia a água de ser congelada.
Bloquear-Congelar-Agua: false

# Este recurso bloqueia a neve e o gelo de serem deretidos.
Bloquear-Derreter-Gelo-E-Neve: false

# Este recurso bloqueia as plantações de serem quebradas ao serem pisoteadas.
Bloquear-Quebrar-Plantacoes-Pulando: false

# Este recurso desativa o tempo do minecraft.
Desativar-Ciclo-Do-Dia: true

# Este recurso desativa as bolas de fogo dos blazes.
Desativar-Dano-Do-Blaze: false

# Este recurso desativa o dano do EnderDragon.
Desativar-Dano-Do-EnderDragon: false

# Este recurso desativa as bolas de fogo dos ghats.
Desativar-Dano-Do-Ghast: false

# Este recurso desativa o dano do Wither e as cabeças lançadas pelo Wither.
Desativar-Dano-Do-Wither: true

# Este recurso desativa os mobs que nascem naturalmente pelo mapa.
Desativar-Mobs-Naturais: true

# Este recurso desativa a propagação das chamas do fogo.
Desativar-Propagacao-Do-Fogo: true

# Este recurso impede que as folhas caiam quando a arvore for quebrada.
Desativar-Queda-Das-Folhas: true

# Este recurso remove a fisica da areia e impede que e la caia.
Desativar-Queda-Da-Areia: false

# Este recurso impede que a água escore para baixo, permitindo apenas escorer para os lados.
Desativar-Flow-Da-Agua-E-Lava: false

# Este recurso desativa a chuva do servidor.
Desativar-Chuva: true

############################################################
# +------------------------------------------------------+ #
# |                   Recursos Gerais                    | #
# +------------------------------------------------------+ #
############################################################
# Este recurso impede que as bigornas quebrem tornando elas infinitas.
Bigorna-Infinita: true

# Este recurso permite renomear itens usando cores (&). 
# OBS: Precisa da permissão system.cornabigorna
Ativar-Cores-Na-Bigorna: true

# Este recurso permite escrever nas placas usando cores (&). 
# OBS: Precisa da permissão system.cornaplaca
Ativar-Cores-Na-Placa: true

# Este recurso impede que os players caiam no Void.
Bloquear-Cair-No-Void: true

# Este recurso impede os Zombies e Esqueletos de pegarem fogo no sol.
Bloquear-Mobs-De-Pegarem-Fogo-Para-O-Sol: false

# Este recurso desativa a fome do jogo.
Desativar-Fome-Nos-Mundos: true

# Estes recursos desativa as mensagens que aparecem quando o player entra, sai ou morre.
Desativar-Mensagem-De-Entrada: true
Desativar-Mensagem-De-Morte: true
Desativar-Mensagem-De-Saida: true

# Este recurso teleporta o player para o Spawn (/setpsawn) ao logar.
Entrar-No-Spawn-Ao-Logar: true

# Este recurso impede o player de criar portais.
Bloquear-Criar-Portal: true

# Este recurso impede o player de se teleportar usando portais.
Bloquear-Teleport-Por-Portal:
  Ativar: true
  NetherPortal: true
  EndPortal: false

############################################################
# +------------------------------------------------------+ #
# |                Configurações Diversas                | #
# +------------------------------------------------------+ #
############################################################
# Este delay é usando em varios comandos como /home /tpa /spawn etc...
# OBS: Para burlar use a permissão: system.semdelay
Delay-Para-Teleportar-Comandos: 5 #segundos

# Este delay é usando no comando /divulgar
# OBS: Para burlar use a permissão: system.bypass.delaydivulgar
Delay-Para-Divulgar: 15 #minutos

Tempo-Para-Expirar-Solicitacao-Tpa: 60 #segundos
Tempo-Para-Poder-Enviar-Outra-Solicitacao-Tpa: 30 #segundos

Limitador-De-Players:
  Ativar: true

  # Não se esqueça de alterar o limite de players na server.propriets
  # Se você colocar limite de 300 deixe pelo menos umas 20 vagas para VIPS.
  # Então coloque 320 na server.propriets
  Limite-De-Players: 300

  # Se o servidor estiver lotado, deseja kickar um player aleatório
  # sem vip para que um vip possa entrar?
  Kickar-Sem-Vip: true
  Tempo-Para-Ser-Kickado-Apos-Aviso: 60 #segundos

# Este recurso impede que o player tome dano por 3 segundos ao se teleportar.
Invencibilidade-Ao-Teleportar: 
  Ativar: true
  Tempo-De-Invencibilidade-Ao-Teleportar: 3 #segundos

# Este recurso faz com que tenha uma chance da cabeça do player dropar ao morrer.
Dropar-Cabeca-Ao-Morrer: 
  Ativar: true
  Chance-De-Dropar-Cabeca-Ao-Morrer: 15

# Este recurso permite os players usarem o comando /fly em determinados mundos
Sistema-De-Fly-Para-Players: true
Mundos-Onde-Pode-Usar-Fly:
  - 'world'
  - 'world_nether'


############################################################
# +------------------------------------------------------+ #
# |                 Sistemas de Spawners                 | #
# +------------------------------------------------------+ #
############################################################
Sistema-De-Spawners: true
Bloquear-Trocar-Tipo-Do-Spawner-Com-Ovo: true
Dropar-Spawner-Ao-Explodir: true
Chance-De-Dropar-Ao-Explodir: 60

############################################################
# +------------------------------------------------------+ #
# |           Mensagem e Title de Boas-Vindas            | #
# +------------------------------------------------------+ #
############################################################
Mensagem-De-Boas-Vindas:
  Ativar: false
  Mensagem:
    - '&6-&e=&6-&e=&6-&e=&6-&e=&6-{ &bSeja Bem Vindo ao Hypixel! &6}-&e=&6-&e=&6-&e=&6-&e=&6-'
    - '&eAdquira CASH e VIP em: &6store.hypixel.net'
    - '&eNos siga no twiiter: &6twiiter.com/hypixel'
    - '&eDivirta-se em nosso TS3: &6ts.hypixel.net'
    # %player% mostra o nome do player.

Title-De-Boas-Vindas:
  Ativar: true
  Titulo: '&6&lHYPIXEL'
  Subtitulo: '&eSEJA BEM-VINDO!'
  # %player% mostra o nome do player.

############################################################
# +------------------------------------------------------+ #
# |                 Mundo VIP do Servidor                | #
# +------------------------------------------------------+ #
############################################################
Ativar-Camarote-Para-Os-Sem-Vip: true

############################################################
# +------------------------------------------------------+ #
# |                   Motd do Servidor                   | #
# +------------------------------------------------------+ #
############################################################
Motd:
  Ativar: true
  Linha1: "&f&lGamer's&6&lBoard &7www.gamersboard.com.br"
  Linha2: "&fA sua comunidade gamer!"

############################################################
# +------------------------------------------------------+ #
# |                   Deletar Comandos                   | #
# +------------------------------------------------------+ #
############################################################
# Este recurso serve para deletar comandos do minecraft ou de outros plugins!

# Para deletar um comando do servidor como por exemplo o /help use:
# - "*:help"
# Isto removeria todos os comandos /help tanto /bukkit:help quanto o /miencraft:help

# Caso você tenha um plugin com o comando /me e quer deletar apenas o /minecraft:me use:
# - "minecraft:me"
# Isto removeria apenas o comando /me do minecraft

# Caso você queira deletar todos os comandos duplicados de um plugin use:
# - "vault:*" 
# Isto iria remover o comando /vault:convert mas iria manter o comando /convert

Deletar-Comandos: true
Lista-Dos-Comandos-Deletados:
   - "*:achievement"
   - "*:blockdata"
   - "*:clone"
   - "*:entitydata"
   - "*:fill"
   - "*:help"
   - "*:me"
   - "*:say"
   - "*:replaceitem"
   - "*:setblock"
   - "*:testfor"
   - "*:testforblock"
   - "*:testforblocks"

############################################################
# +------------------------------------------------------+ #
# |                   Bloquear Comandos                  | #
# +------------------------------------------------------+ #
############################################################
# Este recurso apenas bloqueia os players de usarem os comandos.
# OBS: Para burlar use a permissão: system.bypass.comandobloqueado
Bloquear-Comandos: false
Lista-Dos-Comandos-Bloqueados:
  - '/teste'
  - '/dupar'
  - '/pl'
  - '/plugins'
 
############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Crafts                   | #
# +------------------------------------------------------+ #
############################################################
# Este recurso bloqueia os players de craftarem tais itens.
# OBS: Para burlar use a permissão: system.bypass.craftbloqueado
Bloquear-Crafts: true
Lista-Dos-Crafts-Bloqueados: 
  - '333'
  - '321'
  - '416'
  - '328'
  # Lista de IDs da 1.8: https://www.minecraftinfo.com/idlist.htm

############################################################
# +------------------------------------------------------+ #
# |                    Bloquear Placas                   | #
# +------------------------------------------------------+ #
############################################################
# Caso você queira bloquear que os players digitem em placas basta colocar
# Bloquear-Todas-As-Palavras: true

# Caso você queira bloquear apenas algumas palavras das placas use
# Bloquear-Apenas-Algumas-Palavras: true e depois coloque as palavras na lista

# OBS: Para burlar use a permissão: system.bypass.placabloqueada
Bloquear-Palavras-Em-Placas:
  Ativar: true
  Bloquear-Todas-As-Palavras: false
  Bloquear-Apenas-Algumas-Palavras: true
  Lista-Das-Palavras-Bloqueadas:
    - 'AdminShop'
    - '&0AdminShop'
    - 'puta'

############################################################
# +------------------------------------------------------+ #
# |               Bloquear Nicks Impróprios              | #
# +------------------------------------------------------+ #
############################################################
Bloquear-Nicks-Improprios: true
Nicks-Bloqueados:
  - 'puta'
  - 'vadia'
  - 'AdminShop'
  - 'ServerAdmin'
  # O bloqueador verifica se o nick contem tal palavra.
  # Ou seja se o nick do player contem a palavra "puta" o player é bloqueado de entrar.

############################################################
# +------------------------------------------------------+ #
# |                  Comando /slime                      | #
# +------------------------------------------------------+ #
############################################################
Commando-Slime:
  Esta-Em-SlimeChunk: SLIME_WALK2
  Nao-Esta-Em-SlimeChunk: VILLAGER_NO
  
############################################################
# +------------------------------------------------------+ #
# |                         mcMMO                        | #
# +------------------------------------------------------+ #
############################################################
#Tag no legendchat {mctop}
#Para os nomes das skills ficarem em BR vc precisa estar usando um mcMMO traduzido
mcTopTag:
  Tempo-De-Checagem: 900 #segundos
  Tag: '&9[⚒] '
  
############################################################
# +------------------------------------------------------+ #
# |                         Vault                        | #
# +------------------------------------------------------+ #
############################################################
#Tag no legendchat {magnata}
magnataTag:
  Tempo-De-Checagem: 900 #segundos
  Tag: '&2[$] '
  
############################################################
# +------------------------------------------------------+ #
# |                      LegendChat                      | #
# +------------------------------------------------------+ #
############################################################
CorAutomatica:
  master: "§6"
  gerente: "§4"
  admin: "§c"
  vip1: "§2"
  vip2: "§e"
  #Permissão para escrever em destaque no /g: system.chat.destaque
  #Permissão para usar a cor automatica nas frases: system.chat.cor.<cor> 
  #Exemplo: system.chat.cor.master  --  system.chat.cor.vip1

############################################################
# +------------------------------------------------------+ #
# |                     Auto-Anunciar                    | #
# +------------------------------------------------------+ #
############################################################
Auto-Anuncio: true
Destacar-Anuncio: true
Delay-Entre-Anuncios: 300
Reproduzir-Som-No-Anuncio: true
Som-Do-Anuncio: LEVEL_UP
# Lista de sons do minecraft 1.8 http://docs.codelanx.com/Bukkit/1.8/org/bukkit/Sound.html
# Caso queira pular linha use e escrever 2 linhas no mesmo anuncio use: \n 
Lista-De-Anuncios:
  - '&e&l[Anuncio] &eInscreva-se em nosso canal e fique por dentro de tudo &b&nhttp://bit.ly/hypixel&e!'
  - '&e&l[Anuncio] &eAdquira já seu vip através do nosso site &b&nhttps://hypixel.net/&e!'
  - '&e&l[Anuncio] &eAcesse já nosso fórum e fique por dentro de tudo &b&nhttps://hypixel.net/forums/&e!'
  - '&e&l[Anuncio] &eO evento karaoke ira ocorrer nesta semana! Saiba mais &b&nhttp://bit.ly/karaoke&e!'

############################################################
# +------------------------------------------------------+ #
# |                     Anunciar Morte                   | #
# +------------------------------------------------------+ #
############################################################
Anunciar-Morte: true
Anuncios: 
  Mostrar-Para-Quem-Morreu: true
  Mensagem-Para-Defunto: "&cVocê foi porto por %playerMatou%!"

  Mostrar-Para-Quem-Matou: true
  Mensagem-Para-Matador: "&cVocê matou o player %playerMorreu%!"

  Mostrar-Para-Todo-Servidor: false
  Mensagem-Para-Todos: "&c%playerMorreu% foi morto por %playerMatou%!"

############################################################
# +------------------------------------------------------+ #
# |                      ScoreBoard                      | #
# +------------------------------------------------------+ #
############################################################
ScoreBoard:
  # A scoreboard é estatica e não possui variaveis.
  Ativar: false
  Titulo: "  &6&lHypixel  "
  Linhas:
  - '&eSeja Bem Vindo!'
  - '&r'
  - '&aAdquira VIP e Cash:'
  - '&7store.hypixel.net'

############################################################
# +------------------------------------------------------+ #
# |                       Tablist                        | #
# +------------------------------------------------------+ #
############################################################
Ativar-Tablist: true
Parte-De-Cima: |
  &r 
  &r 
  &6&lHYPIXEL
  &f    hypixel.net
Parte-De-Baixo: |
  &r 
  &6Fórum:&f hypixel.net/forums
  &6Team Speak:&f ts.hypixel.net
  &6Facebook:&f fb.com/Hypixel
  &6Twiiter:&f twitter.com/hypixel
  &r
  &6Adquira VIP e Cash acessando: &fstore.hypixel.net
  &r